### ISSUE TITLE
how can i access sign_in and sign_up api

### ISSUE THREAD

**Issue by uzaif313** [stefatkins/rails-starter-api#4]
i am passing params in below format
```js
{ 
  "users": {
  "email": "test@test.com", 
  "password": "123456"
 }  
}
```

**Comment by stefatkins** [comment]
Hi Uzaif, In a previous commit I updated routes.rb that were nested in a scope in to a namespace but unfortunatley it did not work well with devise. It's fixed for now. Here is how you should format your JSON :
```
{
  "user": {
     "email": "test@test.com",
     "password": "123456"
  }
}
```

**Comment by uzaif313** [comment]
Thanks @stefatkins. its work

**Comment by uzaif313** [comment]
@stefatkins  another question when i hit `sign_in` end point i got below response
```js
{
    "id": 1,
    "email": "uzaif@gmail.com",
    "created_at": "2018-11-07T15:36:59.495Z",
    "updated_at": "2018-11-09T07:02:42.682Z"
}
```

and in response header i got  `jwt`  token like below

```js

authorization → Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwic2NwIjoidXNlciIsImF1ZCI6bnVsbCwiaWF0IjoxNTQxNzQ2OTYyLCJleHAiOjE1NDE3NTA1NjIsImp0aSI6ImNkZDBkYjg5LWM0YzAtNGU2My04MDFjLWJjOWJiNjdhNjI1NyJ9.A0eKMXLgkK4EwHiZpOOpNG0EN2Ywm5lRcNG06TClkZM
```

is this correct flow because i saw lots of rest api send token in response body on `sign_in`
